Alternative_logo_url:
  default: ""
  description:
    en: "The logo image at the top left of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the site title text will be shown."
Alternative_small_logo_url:
  default: ""
  description:
    en: "The small logo image at the top left of your site, seen when scrolling down. Use a square 120 × 120 image. If left blank, a home glyph will be shown."
Alternative_mobile_logo_url:
  default: ""
  description:
    en: "The logo used on mobile version of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the image from the `Alternative_logo_url` setting will be used."
